# Informacion descriptiva del archivo
meta.application=bp4-shopping-service
meta.environment=dev
meta.version=1.0.0

# Configuracion de la base de datos
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://192.168.2.13:33060/bp4_shopping_service_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=MYSQL2011
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql:true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Actuator (Inicio)

# Se exponen todos los endpoints disponibles (/actuator/health, /actuator/metrics, /actuator/beans, etc.).
# Sin esta propiedad, solo los endpoints health y info estan expuestos por defecto.
management.endpoints.web.exposure.include=*

# Se muestra informacion detallada del estado de los componentes de la app (DB, circuit breakers, etc.), incluso sin autenticacion.
management.endpoint.health.show-details=always

# Actuator (Fin)